---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    eqeqeq:
      enabled: false
    no-eq-null:
      enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- test/
- sandbox/
- "**.min.js"
- "**.min.map"