var stencil={stencilHolder:{},define:function(a,c,b,d){var g=function(a,c,b){return{guid:stencil.util.guid(),tagID:a,template:b,childStencils:{},isStandard:!0,destination:c,existingContent:"",clear:function(){$(this.destination).empty().append(this.existingContent)},render:function(a,c,b){if(!Array.isArray(a))if(stencil.util.isObject(a))a=[a];else return stencil.util.log("Stencil - "+this.tagID+": dataset in an invalid format, detected: "+typeof a),!1;else if(null==a||0===a.length)return stencil.util.log("Stencil: no dataset passed in"),
!1;var d=this.destination,e=!1,f;null==b?("none"!==d||"none"!==c&&"fragment"!==c?(b=$(d),f=b.filter(":first").clone()):f=$(document.createElement("div")),e=!0):f=b.find(d);var g=this.template,h=this.childStencils,l=this.isStandard;if(f.length)"append"===c?this.existingContent=f.html():("prepend"===c?this.existingContent=f.html():"none"===c&&b.empty(),f.empty());else return stencil.util.log("Stencil: Destination ID - "+d+" not found!"),!1;a.forEach(function(a,c){a.lpIdx=c;a.ctIdx=c+1;for(var b=g;0<=
b.search(/\{\{[\w.]*\}\}/);)var d=b.match(/\{\{[\w.]*\}\}/)[0],d=d.substring(2,d.length-2),e=stencil.util.getKeyValue(a,d),e=null==e?"":e,b=b.replace("{{"+d+"}}",e);var k=f;l&&(d=stencil.util.createWrapper(f,"stencil-replicator","append"),k=f.find(d));k.append(b);Object.keys(h).forEach(function(c){var b=a[c];null!=a.global&&(Array.isArray(b)?b.forEach(function(b){b.global=a.global}):stencil.util.isObject(b)&&(b.global=a.global));h[c].render(b,null,k)});k.find("select[data-stencilselector]").each(function(){var b=
this.getAttribute("data-stencilselector");stencil.util.selectOption($(this),stencil.util.getKeyValue(a,b))})});"prepend"===c&&f.append(this.existingContent);if(e){stencil.opts.debug||stencil.util.cleanUpStencils(f);if("none"===c||"fragment"===c)return f.children();b.replaceWith(f);return!0}}}},h=function(a){var b=g(a.tagID,a.destination,a.template);Object.keys(a.childStencils).forEach(function(c){b.childStencils[c]=h(a.childStencils[c])});return b},e=$("#"+a);if(null!=stencil.stencilHolder[a])return a=
stencil.stencilHolder[a],e=h(a),null==c&&(c=stencil.util.createWrapper($(a.destination),null==d?stencil.opts.defaultOutputElement:d,"after")),e.destination=c,e;if(!e.length)return stencil.util.log("Stencil: Tag ID '"+a+"' provided is not found!"),null;var k={};stencil.util.log("Stencil: Searching for child stencils in "+a);0!==e.find("stencil").length&&(k=stencil.util.findStencils(e));stencil.util.log("Stencil: Completed child stencil generation for "+a+", "+Object.keys(k).length+" child stencil");
null!=b&&b.forEach(function(a){stencil.util.log("Stencil: Building specified child stencil: "+a);var b=$("#"+a);b.length||stencil.util.log("Stencil: Specified child stencil: "+a+" not found!");b.addClass(a);k[a]=g(a,"."+a,b.html());k[a].isStandard=!1;b.empty()});null==c&&(c=stencil.util.createWrapper(e,null==d?stencil.opts.defaultOutputElement:d,"after"));c=g(a,c,e.html());c.childStencils=k;e.remove();return stencil.stencilHolder[a]=c},build:function(a){a=null==a?$("body"):$("#"+a);return 0===a.length?
(stencil.util.log("Stencil: Unable to start build process as starting element ID cannot be found"),null):stencil.util.findStencils(a)},util:{guid:function(){function a(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}return function(){return a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()}}(),selectOption:function(a,c){a.children().each(function(){this.value==c&&this.setAttribute("selected","")})},outerHTML:function(a){return a.clone().wrap("<p>").parent().html()},createWrapper:function(a,
c,b){var d=stencil.util.guid(),g=document.createElement(c);g.className=""===g.className?d:g.className+" "+d;a[b](g);return c+"."+d},findStencils:function(a){function c(a,b){for(var h=a.childNodes,e=0;e<h.length;e++)"STENCIL"!==h[e].nodeName?c(h[e],b):b[h[e].id]=stencil.define(h[e].id,null,null,"stencil-output")}var b={};c(a.get(0),b);return b},cleanUpStencils:function(a){function c(a){if(-1<a.nodeName.indexOf("STENCIL"))0===a.childNodes.length&&a.parentNode.removeChild(a),$(a).children().unwrap().each(function(){c(this)});
else{a=a.childNodes;for(var d=0;d<a.length;d++)c(a[d])}}a.children().each(function(){c(this)})},changeTag:function(a,c){a.each(function(a){var d=this.outerHTML.replace("/^<"+this.nodeName+"/","<"+c).replace("/</"+this.nodeName+">$/","</"+c+">");a.replaceWith(d)})},getKeyValue:function(a,c){var b;c.split(".").every(function(d,g){b=0===g?null==a[d]?stencil.util.log("Stencil: "+d+" of "+c+" not found"):a[d]:null==b[d]?stencil.util.log("Stencil: "+d+" of "+c+" not found"):b[d];return null!=b?!0:!1});
return b},isObject:function(a){return a===Object(a)},log:function(a){stencil.opts.debug&&console.log(a)}},opts:{debug:!1,defaultOutputElement:"stencil-output"}};