var stencil=stencil||{};stencil.opts=$.extend(stencil.opts||{},function(){return{debug:!0,defaultOutputElement:"stencil-output",fetchTimeout:3E3,ieNs:""}}());
stencil=$.extend(stencil||{},function(){return{stencilHolder:{},fetch:function(a){if(null==a)stencil.util.log("Stencil: No valid URL was passed in");else{var d=$.Deferred();$.ajax({url:a,method:"GET",dataType:"html",timeout:stencil.opts.fetchTimeout}).done(function(c){var b=$(c);0===b.length&&stencil.util.log("Stencil: Unable to parse fetched template at <"+a+">");var e=[];b.each(function(c){"STENCIL"!==this.nodeName&&stencil.util.log("Stencil: Fetched template("+(c+1)+"/"+b.length+") at <"+a+"> is not a stencil template");
c=$(this);c=stencil.define(c[0].id,"none",null,c);e.push(c);d.notify(c)});d.done(e)}).fail(function(c){stencil.util.log("Stencil: Failed to fetched template at <"+a+"> due to "+c.status+":"+c.statusText)});return d.promise()}},define:function(a,d,c,b){var e=function(a,b,c){return{guid:stencil.util.guid(),tagID:a,template:c,childStencils:{},isStandard:!0,destination:b,existingContent:"",clear:function(){$(this.destination).empty().append(this.existingContent)},getChild:function(a){var b=this.childStencils,
c=null;if(0===Object.keys(b).length)return null;0<=Object.keys(b).indexOf(a)?c=b[a]:Object.keys(b).every(function(d){d=b[d].getChild(a);if(null==d)return!0;c=d;return!1});return c},render:function(a,b,c){if(!Array.isArray(a))if(stencil.util.isObject(a))a=[a];else return"undefined"===typeof a?stencil.util.log("Stencil - "+this.tagID+": has no data, skipping..."):stencil.util.log("Stencil - "+this.tagID+": dataset in an invalid format, detected: "+typeof a),!1;else if(null==a||0===a.length)return stencil.util.log("Stencil - "+
this.tagID+": was not passed in data"),!1;var d=this.destination,e=!1,g;if(null==c){c=$(d);if("none"===d||"none"===b||"string"===b||"fragment"===b)if("none"===b||"string"===b||"fragment"===b)g=$(document.createElement("div"));else return stencil.util.log('Stencil: Only render output type "none", "fragment" or "string" is supported for stencils with no destination'),!1;else g=c.filter(":first").clone();e=!0}else g=c.find(d.replace(/\\(?=\{|\})/g,"\\\\\\"));var n=this.template,h=this.childStencils,
k=this.isStandard;if(g.length)"append"===b||"prepend"===b?(this.existingContent=g.html(),g.empty()):"none"===b?(c.empty(),g.empty()):"string"!==b&&"fragment"!==b&&g.empty();else return stencil.util.log("Stencil: Destination ID - "+d+" not found!"),!1;a.forEach(function(a,b){a.lpIdx=b;a.ctIdx=b+1;for(var c=n;0<=c.search(/\{\{[\w.]*\}\}/);)var e=c.match(/\{\{[\w.]*\}\}/)[0],e=e.substring(2,e.length-2),f=stencil.util.getKeyValue(a,e),f=null==f?"":f,c=c.replace("{{"+e+"}}",f);var l=g;k&&(e=stencil.util.createWrapper(g,
"stencil-replicator","append"),l=g.find(e));l.append(c);k||l.removeClass(d.replace(".",""));Object.keys(h).forEach(function(b){var c=a[b];null!=a.global&&(Array.isArray(c)?c.forEach(function(b){b.global=a.global}):stencil.util.isObject(c)&&(c.global=a.global));h[b].render(c,null,l)});l.find("select[data-stencilselector]").each(function(){var b=this.getAttribute("data-stencilselector");stencil.util.selectOption($(this),stencil.util.getKeyValue(a,b))})});"prepend"===b&&g.append(this.existingContent);
if(e){stencil.util.cleanUpStencils(g);if("none"===b||"fragment"===b)return g.children();if("string"===b)return g.html();"append"!==b&&c.empty();c.append(g.children());return!0}}}},f=function(a){var b=e(a.tagID,a.destination,a.template);Object.keys(a.childStencils).forEach(function(c){b.childStencils[c]=f(a.childStencils[c])});return b},h;if(null!=stencil.stencilHolder[a]){a=stencil.stencilHolder[a];var k=f(a);null==d&&(d=stencil.util.createWrapper($(a.destination),null==c?stencil.opts.defaultOutputElement:
c,"after"));k.destination=d;return k}k=b||$("#"+stencil.util.escapeCSS(a));if(k.length)null==d&&(d=stencil.util.createWrapper(k,null==c?stencil.opts.defaultOutputElement:c,"after")),b=k.detach();else return stencil.util.log("Stencil: Tag ID '"+a+"' provided is not found!"),null;null!=b.attr("data-childStencil")&&""!=b.attr("data-childStencil")&&(null==h&&(h=[]),b.attr("data-childStencil").split(" ").forEach(function(a){""!=a&&h.push(a)}));var m={};stencil.util.log("Stencil: Searching for child stencils in "+
a);0!==b.find("stencil").length&&(m=stencil.util.findStencils(b));stencil.util.log("Stencil: Completed child stencil generation for "+a+", "+Object.keys(m).length+" child stencil");null!=h&&h.forEach(function(a){stencil.util.log("Stencil: Building specified child stencil: "+a);var c=b.find("#"+stencil.util.escapeCSS(a));if(c.length){var d=stencil.util.guid();c.addClass(d);m[a]=e(a,"."+d,c.html());m[a].isStandard=!1;c.empty()}else stencil.util.log("Stencil: Specified child stencil: "+a+" not found!")});
d=e(a,d,b.html());d.childStencils=m;return stencil.stencilHolder[a]=d},build:function(a){a=null==a?$("body"):$("#"+a);return 0===a.length?(stencil.util.log("Stencil: Unable to start build process as starting element ID cannot be found"),null):stencil.util.findStencils(a)},util:{guid:function(){var a=(new Date).getTime();window.performance&&"function"===typeof window.performance.now&&(a+=performance.now());return"stencil-"+"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(d){var c=(a+
16*Math.random())%16|0;a=Math.floor(a/16);return("x"==d?c:c&3|8).toString(16)})},selectOption:function(a,d){a.children().each(function(){if(this.value==d)return this.setAttribute("selected",""),!1})},outerHTML:function(a){return a.clone().wrap("<p>").parent().html()},createWrapper:function(a,d,c){var b=stencil.util.guid(),e=document.createElement(stencil.opts.ieNs+d);e.className=""===e.className?b:e.className+" "+b;a[c](e);return stencil.util.escapeCSS(stencil.opts.ieNs)+d+"."+b},findStencils:function(a){function d(a,
c){for(var f=a.childNodes,h=0;h<f.length;h++){var k;k=f[h];k="STENCIL"===k.nodeName||"stencil"===k.nodeName?!0:!1;k?c[f[h].id]=stencil.define(f[h].id,null,"stencil-output",$(f[h])):d(f[h],c)}}var c={};d(a.get(0),c);return c},cleanUpStencils:function(a){function d(a){if(function(a){return 0<=a.nodeName.indexOf("STENCIL")||0<=a.nodeName.indexOf("stencil")?!0:!1}(a))0===a.childNodes.length&&a.parentNode.removeChild(a),$(a).children().unwrap().each(function(){d(this)});else{a=a.childNodes;for(var b=0;b<
a.length;b++)d(a[b])}}a.children().each(function(){d(this)})},escapeCSS:function(a){a=String(a);for(var d=a.length,c=-1,b,e="",f=a.charCodeAt(0);++c<d;){b=a.charCodeAt(c);if(0==b)throw new InvalidCharacterError("Invalid character: the input contains U+0000.");e=1<=b&&31>=b||127==b||0==c&&48<=b&&57>=b||1==c&&48<=b&&57>=b&&45==f?e+("\\"+b.toString(16)+" "):128<=b||45==b||95==b||48<=b&&57>=b||65<=b&&90>=b||97<=b&&122>=b?e+a.charAt(c):e+("\\"+a.charAt(c))}return e},getKeyValue:function(a,d){var c;d.split(/[\.\[\]]/).every(function(b,
e){if(""===b)return!0;c=0===e?null==a[b]?stencil.util.log("Stencil: "+b+" of "+d+" not found"):a[b]:null==c[b]?stencil.util.log("Stencil: "+b+" of "+d+" not found"):c[b];return null!=c?!0:!1});return c},isIE:function(){var a=navigator.userAgent.toLowerCase();return-1!=a.indexOf("msie")?parseInt(a.split("msie")[1]):!1},isObject:function(a){return a===Object(a)},log:function(a){stencil.opts.debug&&console.log(a)}}}}());
(function(){var a=stencil.util.isIE();0!=a&&10>a&&(document.createElement("stencil"),document.createElement("stencil-replicator"),document.createElement("stencil-output"),stencil.opts.ieNs="STENCIL:")})();
//stencil.js - version 15 - Kingston Chan https://github.com/kgston/stencil.JS - Released under the MIT licence
//# sourceMappingURL=stencil-15.0-min.map